### ISSUE TITLE
tried 0.1.6 but got Installer is Broken error message

### ISSUE THREAD

**Issue by ftctechnh** [dmssargent/AppInstaller#4]
![image](https://cloud.githubusercontent.com/assets/12596789/17411606/f3ce3b06-5a46-11e6-97f8-8f4ba6eadeea.png)

**Comment by dmssargent** [comment]
This was fixed in fed7914, release v0.1.6.1-beta

The installer places files in the right directory, `%localappdata%\AppInstaller\0.1.6`, however the rest of the installation process fails. You have to manually execute `%localappdata%\AppInstaller\0.1.6\APKInstaller.exe` to run the program.
