### ISSUE TITLE
Shortcut to AppInstaller did not initially appear on Desktop

### ISSUE THREAD

**Issue by ftctechnh** [dmssargent/AppInstaller#6]
A user downloaded and installed the AppInstaller software (0.1.7.1).  He noted that at first, no icon for the application was visible on his desktop.  He is using a Win 10 machine.  He said that after he shut the app down the first time, when he launched the app the second time, a shortcut on the desktop appeared for the app.

**Comment by dmssargent** [comment]
That shouldn't be happening; i will look into it.

**Comment by dmssargent** [comment]
I can't reproduce this issue with the 0.1.7.1 software. On my Win10 machine, it does create an shortcut on the desktop on first run. Is the shortcut being created in `%userprofile%\Desktop` and the installer just isn't refreshing the Desktop?
